/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package program_interface;

import java.awt.Color;
import java.io.File;
import login_interface.login_ui;
import java.util.Scanner;
import java.io.*;
import javax.swing.JOptionPane;


/**
 *
 * @author 6704218
 */
public class program_payment extends javax.swing.JFrame {

    public program_payment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        payment_select = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        next_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        tm_panel = new javax.swing.JPanel();
        tm_select_btn = new javax.swing.JRadioButton();
        phone_input = new javax.swing.JTextField();
        bank_panel = new javax.swing.JPanel();
        bank_select_btn = new javax.swing.JRadioButton();
        scanpay_Btn = new javax.swing.JButton();
        card_panel = new javax.swing.JPanel();
        card_select_btn = new javax.swing.JRadioButton();
        name_input = new javax.swing.JTextField();
        cardnum_input = new javax.swing.JTextField();
        expiry_date_input = new javax.swing.JTextField();
        security_input = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        next_btn.setBackground(new java.awt.Color(204, 255, 204));
        next_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        next_btn.setForeground(new java.awt.Color(0, 153, 0));
        next_btn.setText("Comfirm Order");
        next_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                next_btnMouseClicked(evt);
            }
        });

        back_btn.setBackground(new java.awt.Color(153, 153, 153));
        back_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        back_btn.setText("Back");
        back_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_btnMouseClicked(evt);
            }
        });
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        tm_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        payment_select.add(tm_select_btn);
        tm_select_btn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tm_select_btn.setText(" True Money");
        tm_select_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tm_select_btnActionPerformed(evt);
            }
        });

        phone_input.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phone_input.setForeground(new java.awt.Color(153, 153, 153));
        phone_input.setText("Phone");
        phone_input.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phone_inputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phone_inputFocusLost(evt);
            }
        });
        phone_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone_inputActionPerformed(evt);
            }
        });
        phone_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phone_inputKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout tm_panelLayout = new javax.swing.GroupLayout(tm_panel);
        tm_panel.setLayout(tm_panelLayout);
        tm_panelLayout.setHorizontalGroup(
            tm_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tm_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tm_select_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(phone_input, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tm_panelLayout.setVerticalGroup(
            tm_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tm_panelLayout.createSequentialGroup()
                .addGroup(tm_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tm_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tm_select_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tm_panelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(phone_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bank_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        payment_select.add(bank_select_btn);
        bank_select_btn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bank_select_btn.setText(" Promptpay");
        bank_select_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bank_select_btnActionPerformed(evt);
            }
        });

        scanpay_Btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        scanpay_Btn.setText("QR Code");

        javax.swing.GroupLayout bank_panelLayout = new javax.swing.GroupLayout(bank_panel);
        bank_panel.setLayout(bank_panelLayout);
        bank_panelLayout.setHorizontalGroup(
            bank_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bank_panelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(bank_select_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scanpay_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        bank_panelLayout.setVerticalGroup(
            bank_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bank_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bank_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bank_select_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scanpay_Btn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        card_panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        payment_select.add(card_select_btn);
        card_select_btn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        card_select_btn.setText(" Credit Card");
        card_select_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                card_select_btnActionPerformed(evt);
            }
        });

        name_input.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        name_input.setForeground(new java.awt.Color(153, 153, 153));
        name_input.setText("Name");
        name_input.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                name_inputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                name_inputFocusLost(evt);
            }
        });
        name_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_inputActionPerformed(evt);
            }
        });

        cardnum_input.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cardnum_input.setForeground(new java.awt.Color(153, 153, 153));
        cardnum_input.setText("Card Number");
        cardnum_input.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cardnum_inputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cardnum_inputFocusLost(evt);
            }
        });
        cardnum_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardnum_inputActionPerformed(evt);
            }
        });

        expiry_date_input.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        expiry_date_input.setForeground(new java.awt.Color(153, 153, 153));
        expiry_date_input.setText("Expiry Date (MM/YY)");
        expiry_date_input.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                expiry_date_inputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                expiry_date_inputFocusLost(evt);
            }
        });
        expiry_date_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expiry_date_inputActionPerformed(evt);
            }
        });

        security_input.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        security_input.setForeground(new java.awt.Color(153, 153, 153));
        security_input.setText("Security Code");
        security_input.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                security_inputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                security_inputFocusLost(evt);
            }
        });
        security_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                security_inputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout card_panelLayout = new javax.swing.GroupLayout(card_panel);
        card_panel.setLayout(card_panelLayout);
        card_panelLayout.setHorizontalGroup(
            card_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(card_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(card_panelLayout.createSequentialGroup()
                        .addComponent(expiry_date_input, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(security_input, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, card_panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(card_select_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(cardnum_input, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(name_input, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(16, 16, 16))
        );
        card_panelLayout.setVerticalGroup(
            card_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(card_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(card_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(card_select_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardnum_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(card_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expiry_date_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(security_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 203, Short.MAX_VALUE)
                        .addComponent(next_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tm_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(card_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bank_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(tm_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(bank_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(card_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(next_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_btnMouseClicked
        program_order new_open=new program_order();
        this.setVisible(false);
        new_open.setVisible(true);
        
    }//GEN-LAST:event_back_btnMouseClicked

    private void next_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_next_btnMouseClicked
        if(!tm_select_btn.isSelected()){
            if(phone_input.getText().length()>0){
                JOptionPane.showMessageDialog(null, "Please select True Money payment");
            }
            if(!bank_select_btn.isSelected()) {
                if(!card_select_btn.isSelected()) {
                    JOptionPane.showMessageDialog(null, "Please select your payment");
                    if(cardnum_input.getText().length()>0||name_input.getText().length()>0||security_input.getText().length()>0||expiry_date_input.getText().length()>0){
                        JOptionPane.showMessageDialog(null, "Please select Credit Card payment");
                    }
                }
            }
        }
        if(tm_select_btn.isSelected()){
            if(phone_input.getText().length()==7){
                login_interface.login_ui new_open=new login_interface.login_ui();
                this.setVisible(false);
                new_open.setVisible(true);
                JOptionPane.showMessageDialog(null, "Ordered Successfully!");
            }
            if(phone_input.getText().length()!=7){
                JOptionPane.showMessageDialog(null, "Your phone number incorrect! Please Try again");
            }
        }
        
        if(bank_select_btn.isSelected()){
            login_interface.login_ui new_open=new login_interface.login_ui();
            this.setVisible(false);
            new_open.setVisible(true);
            JOptionPane.showMessageDialog(null, "Ordered Successfully!");
        }
        if(card_select_btn.isSelected()){
            if(cardnum_input.getText().length()==16&&name_input.getText().length()>3&&security_input.getText().length()==3&&expiry_date_input.getText().length()==4){
                login_interface.login_ui new_open=new login_interface.login_ui();
                this.setVisible(false);
                new_open.setVisible(true);
                JOptionPane.showMessageDialog(null, "Ordered Successfully!");
            }
            if(cardnum_input.getText().length()!=16||name_input.getText().length()<3||security_input.getText().length()!=3||expiry_date_input.getText().length()!=4){
                JOptionPane.showMessageDialog(null, "Please check your credit card info! and Try again");
            }
        }
    }//GEN-LAST:event_next_btnMouseClicked

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_back_btnActionPerformed

    private void tm_select_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tm_select_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tm_select_btnActionPerformed

    private void card_select_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_card_select_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_card_select_btnActionPerformed

    private void bank_select_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bank_select_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bank_select_btnActionPerformed

    private void phone_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phone_inputActionPerformed

    private void phone_inputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phone_inputFocusGained
        if(phone_input.getText().equals("Phone")){
            phone_input.setText("");
            phone_input.setForeground(Color.black);
        }

    }//GEN-LAST:event_phone_inputFocusGained

    private void phone_inputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phone_inputFocusLost
        if(phone_input.getText().equals("")){
            phone_input.setText("Phone");
            phone_input.setForeground(new java.awt.Color(153,153,153));
        }
    }//GEN-LAST:event_phone_inputFocusLost

    private void name_inputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_name_inputFocusGained
        if(name_input.getText().equals("Name")){
            name_input.setText("");
            name_input.setForeground(Color.black);
        }
    }//GEN-LAST:event_name_inputFocusGained

    private void name_inputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_name_inputFocusLost
        if(name_input.getText().equals("")){
            name_input.setText("Name");
            name_input.setForeground(new java.awt.Color(153,153,153));
        }
    }//GEN-LAST:event_name_inputFocusLost

    private void name_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_inputActionPerformed

    private void cardnum_inputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cardnum_inputFocusGained
       if(cardnum_input.getText().equals("Card Number")){
            cardnum_input.setText("");
            cardnum_input.setForeground(Color.black);
        }
    }//GEN-LAST:event_cardnum_inputFocusGained

    private void cardnum_inputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cardnum_inputFocusLost
        if(cardnum_input.getText().equals("")){
            cardnum_input.setText("Card Number");
            cardnum_input.setForeground(new java.awt.Color(153,153,153));
        }
    }//GEN-LAST:event_cardnum_inputFocusLost

    private void cardnum_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardnum_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardnum_inputActionPerformed

    private void expiry_date_inputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_expiry_date_inputFocusGained
        if(expiry_date_input.getText().equals("Expiry Date (MM/YY)")){
            expiry_date_input.setText("");
            expiry_date_input.setForeground(Color.black);
        }
    }//GEN-LAST:event_expiry_date_inputFocusGained

    private void expiry_date_inputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_expiry_date_inputFocusLost
        if(expiry_date_input.getText().equals("")){
            expiry_date_input.setText("Expiry Date (MM/YY)");
            expiry_date_input.setForeground(new java.awt.Color(153,153,153));
        }
    }//GEN-LAST:event_expiry_date_inputFocusLost

    private void expiry_date_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expiry_date_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expiry_date_inputActionPerformed

    private void security_inputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_security_inputFocusGained
        if(security_input.getText().equals("Security Code")){
            security_input.setText("");
            security_input.setForeground(Color.black);
        }
    }//GEN-LAST:event_security_inputFocusGained

    private void security_inputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_security_inputFocusLost
        if(security_input.getText().equals("")){
            security_input.setText("Security Code");
            security_input.setForeground(new java.awt.Color(153,153,153));
        }
    }//GEN-LAST:event_security_inputFocusLost

    private void security_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_security_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_security_inputActionPerformed

    private void phone_inputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phone_inputKeyPressed
       
    }//GEN-LAST:event_phone_inputKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new program_payment().setVisible(true);
                
                
            }
        });
    }
    
    private final int transfer1=program_order.amt1;
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JPanel bank_panel;
    private javax.swing.JRadioButton bank_select_btn;
    private javax.swing.JPanel card_panel;
    private javax.swing.JRadioButton card_select_btn;
    private javax.swing.JTextField cardnum_input;
    private javax.swing.JTextField expiry_date_input;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField name_input;
    private javax.swing.JButton next_btn;
    private javax.swing.ButtonGroup payment_select;
    private javax.swing.JTextField phone_input;
    private javax.swing.JButton scanpay_Btn;
    private javax.swing.JTextField security_input;
    private javax.swing.JPanel tm_panel;
    private javax.swing.JRadioButton tm_select_btn;
    // End of variables declaration//GEN-END:variables

    private void close() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    
}
